[RW-6368][risk=low]: Add RAS client id and hostname into config
all-of-us/workbench pull request #4652
Opened 2021-03-05 02:46 UTC by yonghaoy

Description:

---
**PR checklist**

- [ ] This PR meets the Acceptance Criteria in the JIRA story
- [ ] The JIRA story has been moved to Dev Review
- [ ] This PR includes appropriate unit tests
- [ ] I have run and tested this change locally
- [ ] I have run the E2E tests on ths change against my local UI and/or API server with `yarn test-local` or [yarn test-local-devup](https://github.com/all-of-us/workbench/blob/master/e2e/README.md#examples)
- [ ] If this includes a UI change, I have taken screen recordings or screenshots of the new behavior and notified the PO and UX designer
- [ ] If this includes an API change, I have updated the appropriate Swagger definitions and notified API consumers
- [ ] If this includes a new feature flag, I have created and linked new JIRA tickets to (a) turn on the feature flag and (b) remove it later

2021-03-05 02:49 UTC, yonghaoy commented on api/config/config_test.json
> +    "host": "https:\/\/stsstg.nih.gov",
both are RAS staging. They only have one instance. And they created registered us with one client ID and secret, but with different redirect URL. (aou-test/ras-callback vs localhost:4200/ras-callback)

2021-03-05 18:20 UTC, jmthibault79 requested changes
Please add config values for all environments.  Can use "not implemented" or similar but we do need to have values present.

2021-03-05 22:21 UTC, jmthibault79 approved these changes

2021-03-09 18:25 UTC, calbach approved these changes

2021-03-09 18:25 UTC, calbach commented on api/config/config_perf.json
> +    "host": "not implemented",
nit: personally I'd just prefer empty string here, I'd say that's the usual convention we use for new flags which don't have values yet in higher environments

2021-03-10 17:32 UTC, merged