[RW-6893][risk=no] Upgrade Google Cloud Storage java lib to latest 1.xx
all-of-us/workbench pull request #5666
Opened 2021-09-28 18:09 UTC by calbach

Per sysadmin team, GCS <1.114 has issues interacting with some buckets. The issue seems unlikely to affect us, but upgrading to be safe.

2021-09-29 12:18 UTC, jmthibault79 requested changes
dev-up fails with many stacktraces.  They all seem to be ultimately this:
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'getCloudLogging' defined in class path resource [org/pmiops/workbench/audit/ActionAuditSpringConfiguration.class]: Bean instantiation via
 factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.google.cloud.logging.Logging]: Factory method 'getCloudLogging' threw exception; nested exception is
 com.google.cloud.logging.LoggingException: java.lang.IllegalStateException: getTransportChannel() called when needsExecutor() is true
```

2021-09-30 12:32 UTC, jmthibault79 commented
Lots of dev-up spam like this, but it seems to run ok otherwise
```
WARNING: Exception thrown by the service export io.opencensus.exporter.trace.stackdriver.StackdriverTraceExporter
java.lang.AbstractMethodError: com/google/api/gax/retrying/RetryingContext.getRetrySettings()Lcom/google/api/gax/retrying/RetrySettings;
        at com.google.api.gax.retrying.ExponentialRetryAlgorithm.createFirstAttempt(ExponentialRetryAlgorithm.java:90)
        at com.google.api.gax.retrying.RetryAlgorithm.createFirstAttempt(RetryAlgorithm.java:112)
        at com.google.api.gax.retrying.BasicRetryingFuture.<init>(BasicRetryingFuture.java:80)
        at com.google.api.gax.retrying.CallbackChainRetryingFuture.<init>(CallbackChainRetryingFuture.java:63)
        at com.google.api.gax.retrying.ScheduledRetryingExecutor.createFuture(ScheduledRetryingExecutor.java:102)
        at com.google.api.gax.rpc.RetryingCallable.futureCall(RetryingCallable.java:61)
        at com.google.api.gax.rpc.RetryingCallable.futureCall(RetryingCallable.java:41)
        at com.google.api.gax.tracing.TracedUnaryCallable.futureCall(TracedUnaryCallable.java:75)
        at com.google.api.gax.rpc.UnaryCallable$1.futureCall(UnaryCallable.java:126)
        at com.google.api.gax.rpc.UnaryCallable.futureCall(UnaryCallable.java:87)
        at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
        at com.google.cloud.trace.v2.TraceServiceClient.batchWriteSpans(TraceServiceClient.java:234)
        at com.google.cloud.trace.v2.TraceServiceClient.batchWriteSpans(TraceServiceClient.java:182)
        at io.opencensus.exporter.trace.stackdriver.StackdriverV2ExporterHandler.export(StackdriverV2ExporterHandler.java:444)
        at io.opencensus.implcore.trace.export.SpanExporterImpl$Worker.onBatchExport(SpanExporterImpl.java:248)
        at io.opencensus.implcore.trace.export.SpanExporterImpl$Worker.exportBatches(SpanExporterImpl.java:350)
        at io.opencensus.implcore.trace.export.SpanExporterImpl$Worker.run(SpanExporterImpl.java:290)
        at com.google.appengine.tools.development.RequestThreadFactory$1$1$2.run(RequestThreadFactory.java:114)
        at java.security.AccessController.doPrivileged(AccessController.java:708)
        at com.google.appengine.tools.development.RequestThreadFactory$1$1.run(RequestThreadFactory.java:110)
```

2021-09-30 16:48 UTC, calbach commented
I'll resend the PR when the issues are resolved; I'm just occasionally trying things when I have the chance in the background

2021-12-05 19:59 UTC, jmthibault79 commented
#5949 takes us to 2.2.1 - does that resolve the sysadmins' concerns?

2021-12-06 17:40 UTC, calbach commented
Yes - thank you!

2021-12-06 17:40 UTC, closed without merging