[RW-7834][risk=no] Require TOS acceptance on login when users are not Terra-TOS compliant
all-of-us/workbench pull request #6507
Opened 2022-03-29 17:56 UTC by NehaBroad

Description:

---
**PR checklist**

- [ ] This PR meets the Acceptance Criteria in the JIRA story
- [ ] The JIRA story has been moved to Dev Review
- [ ] This PR includes appropriate unit tests
- [ ] I have added explanatory comments where the logic is not obvious
- [ ] I have run and tested this change locally, and my testing process is described here
- [ ] If this includes a new feature flag, I have created and linked new JIRA tickets to (a) turn on the feature flag and (b) remove it later
- [ ] If this includes an API change, I have run the E2E tests on this change against my local server with [yarn test-local](https://github.com/all-of-us/workbench/blob/master/e2e/README.md#examples) because this PR won't be covered by the CircleCI tests 
- [ ] If this includes a UI change, I have taken screen recordings or screenshots of the new behavior and notified the PO and UX designer in [Slack](https://pmi-engteam.slack.com/archives/C02MWP2RN5P)
- [ ] If this change impacts deployment safety (e.g. removing/altering APIs which are in use) I have documented these in the description
- [ ] If this includes an API change, I have updated the appropriate Swagger definitions and updated the appropriate API consumers
  * AoU UI
  * [Perf tests](https://github.com/broadinstitute/mcnulty/blob/develop/src/test/scala/services/AoU.scala)
  * [Researcher Directory export](https://github.com/all-of-us/workbench/wiki/Researcher-Directory-(RDR-export))
  * Cron tasks - for Offline*Controllers
  * SumoLogic - for EgressAlert

2022-03-29 19:47 UTC, jmthibault79 requested changes
Please update UserServiceTest with the following:
* update `test_validateTermsOfService_dbUser()` to check for return value
* add a version of this test ^ where `mockFireCloudService.getUserTermsOfServiceStatus()` returns false
* add standalone tests for `validateAllOfUsTermsOfServiceVersion()`

2022-03-29 19:47 UTC, jmthibault79 commented on api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
> +    return userTermsOfServiceDao
woo

2022-03-30 13:44 UTC, NehaBroad commented on api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java
> +    when(mockFireCloudService.getUserTermsOfServiceStatus()).thenReturn(false);
test_validateTermsOfService_dbUser_hasNotAcceptedTerraTOS()  line # 593

2022-03-30 14:11 UTC, jmthibault79 commented on api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java
> +    when(mockFireCloudService.getUserTermsOfServiceStatus()).thenReturn(false);
right!  sorry

2022-03-30 14:11 UTC, jmthibault79 approved these changes

2022-03-30 14:26 UTC, merged