[RW-9642][risk=no]   Warn Users that Jobs may be Terminated when Deleting Cromwell App
all-of-us/workbench pull request #7497
Opened 2023-03-16 15:51 UTC by NehaBroad

Description:

---
**PR checklist**

- [ ] This PR meets the Acceptance Criteria in the JIRA story
- [ ] The JIRA story has been moved to Dev Review
- [ ] This PR includes appropriate unit tests
- [ ] I have added explanatory comments where the logic is not obvious
- [ ] I have run and tested this change locally, and my testing process is described here
- [ ] If this includes a new feature flag, I have created and linked new JIRA tickets to (a) turn on the feature flag and (b) remove it later
- [ ] If this includes an API change, I have run the E2E tests on this change against my local server with [yarn test-local](https://github.com/all-of-us/workbench/blob/master/e2e/README.md#examples) because this PR won't be covered by the CircleCI tests 
- [ ] If this includes a UI change, I have taken screen recordings or screenshots of the new behavior and notified the PO and UX designer in [Slack](https://pmi-engteam.slack.com/archives/C02MWP2RN5P)
- [ ] If this change impacts deployment safety (e.g. removing/altering APIs which are in use) I have documented these in the description
- [ ] If this includes an API change, I have updated the appropriate Swagger definitions and updated the appropriate API consumers
  * AoU UI
  * [Perf tests](https://github.com/broadinstitute/mcnulty/blob/develop/src/test/scala/services/AoU.scala)
  * [Researcher Directory export](https://github.com/all-of-us/workbench/wiki/Researcher-Directory-(RDR-export))
  * Cron tasks - for Offline*Controllers
  * SumoLogic - for EgressAlert

2023-03-21 18:17 UTC, jmthibault79 requested changes
Command given does not work.

2023-03-21 18:17 UTC, jmthibault79 commented on ui/src/app/components/apps-panel/delete-cromwell-modal.tsx
> +  const cromshell_job_check_command = 'cromshell-alpha list -u';
<img width="555" alt="Screenshot 2023-03-21 at 2 16 45 PM" src="https://user-images.githubusercontent.com/2701406/226704196-9c5a320f-0bb3-4c85-bbee-1bc0962b38ef.png">

2023-03-21 18:25 UTC, jmthibault79 commented on ui/src/app/components/apps-panel/delete-cromwell-modal.tsx
> +          Do you still want to delete Cromwell?
"your Cromwell environment"

2023-04-10 18:31 UTC, closed without merging

2023-04-10 18:32 UTC, NehaBroad commented
shoot i was trying some command and it merged it.