[RW-9518][risk=no] [tests] Cromwell / User App tests
all-of-us/workbench pull request #7613
Opened 2023-04-24 14:39 UTC by NehaBroad

Future work to mark the story as done:
1) e2e for R

Improvements:
1) Correct snippet to use cromshell-alpha not cromshell_alpha 
3) Should we clean up the cromshell jobs before deleting cromwell? 
4) Having Notebook upload multiple files rather than one at a time
 

Description:

---
**PR checklist**

- [x] This PR meets the Acceptance Criteria in the JIRA story
- [ ] The JIRA story has been moved to Dev Review
- [ ] This PR includes appropriate unit tests
- [x] I have added explanatory comments where the logic is not obvious
- [x] I have run and tested this change locally, and my testing process is described here
- [ ] If this includes a new feature flag, I have created and linked new JIRA tickets to (a) turn on the feature flag and (b) remove it later
- [ ] If this includes an API change, I have run the E2E tests on this change against my local server with [yarn test-local](https://github.com/all-of-us/workbench/blob/master/e2e/README.md#examples) because this PR won't be covered by the CircleCI tests 
- [ ] If this includes a UI change, I have taken screen recordings or screenshots of the new behavior and notified the PO and UX designer in [Slack](https://pmi-engteam.slack.com/archives/C02MWP2RN5P)
- [ ] If this change impacts deployment safety (e.g. removing/altering APIs which are in use) I have documented these in the description
- [ ] If this includes an API change, I have updated the appropriate Swagger definitions and updated the appropriate API consumers
  * AoU UI
  * [Perf tests](https://github.com/broadinstitute/mcnulty/blob/develop/src/test/scala/services/AoU.scala)
  * [Researcher Directory export](https://github.com/all-of-us/workbench/wiki/Researcher-Directory-(RDR-export))
  * Cron tasks - for Offline*Controllers
  * SumoLogic - for EgressAlert

2023-04-24 15:43 UTC, NehaBroad reviewed
Not sure if we need the other test Create and delete a Cromwell GKE app..thoughts?

2023-04-27 19:03 UTC, jmthibault79 requested changes

2023-04-27 19:03 UTC, jmthibault79 commented on e2e/app/page/notebook-page.ts
> +  async selectSnippet(snippetsName: string, subCategory: string): Promise<void> {
Thanks for figuring this out!

2023-04-27 20:12 UTC, jmthibault79 commented on e2e/tests/nightly/gke-apps/cromwell.spec.ts
> +    await findOrCreateWorkspace(page, { workspaceName });
we should use a separate workspace for this, so they don't interfere with each other

2023-04-28 01:42 UTC, NehaBroad commented on e2e/tests/nightly/gke-apps/cromwell.spec.ts
> +    const isDeleted = cromwellPanel.deleteCromwellGkeApp();
Done

2023-04-28 01:42 UTC, NehaBroad commented on e2e/tests/nightly/gke-apps/cromwell.spec.ts
> +import expect from 'expect';
removed expect

2023-04-28 01:42 UTC, NehaBroad commented on e2e/resources/cromwell/cromwell.wdl
> +version 1.0
updated wdl

2023-04-28 01:42 UTC, NehaBroad commented on e2e/resources/cromwell/cromwell.json
> +{}
done: changed to empty.json

2023-04-28 01:42 UTC, NehaBroad commented on e2e/app/sidebar/cromwell-configuration-panel.ts
> +  async deleteCromwellGkeApp(): Promise<boolean> {
Moved it to apps-panel

2023-04-28 01:42 UTC, NehaBroad commented on e2e/app/sidebar/cromwell-configuration-panel.ts
> +import expect from 'expect';
Done

2023-04-28 01:42 UTC, NehaBroad commented on e2e/app/sidebar/apps-panel.ts
> +import expect from 'expect';
done

2023-04-28 13:28 UTC, jmthibault79 commented on e2e/app/sidebar/apps-panel.ts
> +import expect from 'expect';
this is not done.

2023-04-28 14:16 UTC, jmthibault79 approved these changes

2023-05-02 13:53 UTC, merged