Eric/introduce identity
all-of-us/workbench pull request #7823
Opened 2023-07-20 21:02 UTC by evrii

---
**PR checklist**

- [ ] I have included an issue ID or "no ticket" in the PR title as outlined in [CONTRIBUTING.md](https://github.com/all-of-us/workbench/blob/main/.github/CONTRIBUTING.md).
- [ ] I have included a risk tag of the form `[risk=no|low|moderate|severe]` in the PR title as outlined in [CONTRIBUTING.md](https://github.com/all-of-us/workbench/blob/main/.github/CONTRIBUTING.md).
- [ ] I have manually tested this change and my testing process is described above.
- [ ] This change includes appropriate automated tests, and I have documented any behavior that cannot be tested with code.
- [ ] I have added explanatory comments where the logic is not obvious.
- One or more of the following is true:
  - [ ] This change is intended to complete a JIRA story, so I have checked that all AC are met for that story.
  - [ ] This change fixes a bug, so I have ensured the steps to reproduce are in the Jira ticket or provided above.
  - [ ] This change impacts deployment safety (e.g. removing/altering APIs which are in use), so I have documented the impacts in the description.
  - [ ] This change includes a new feature flag, so I have created and linked new JIRA tickets to (a) turn on the feature flag and (b) remove it later.
  - [ ] This change modifies the UI, so I have taken screenshots or recordings of the new behavior and notified the PO and UX designer in [Slack](https://pmi-engteam.slack.com/archives/C02MWP2RN5P).
  - [ ] This change modifies API behavior, so I have run the relevant E2E tests locally because API changes are not covered by our PR checks.
  - [ ] None of the above apply to this change.

2023-07-21 18:29 UTC, evrii commented on api/src/main/resources/workbench-api.yaml
> +      identityBypassTime:
Is it a problem to send the reporting user more data than they are expecting? I know that we should coordinate with them when removing something.

2023-07-25 20:31 UTC, evrii commented on api/src/main/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceImpl.java
> +                + "  uami.identity_bypass_time,\n"
Is there any problem with sending the reporting team more data than they are expecting?

2023-07-26 21:00 UTC, Peter-Lavigne requested changes
> Also, ensure that completing and/or bypassing a user's LOGINGOV module does the same for the user in the database.

LGTM, other than this specific feature not working as intended. I can help debug as needed tomorrow.

2023-07-27 14:11 UTC, Peter-Lavigne approved these changes

2023-07-27 17:28 UTC, merged