Eric/rw 10488
all-of-us/workbench pull request #8274
Opened 2024-01-05 21:26 UTC by evrii

---
**PR checklist**

- [ ] I have included an issue ID or "no ticket" in the PR title as outlined in [CONTRIBUTING.md](https://github.com/all-of-us/workbench/blob/main/.github/CONTRIBUTING.md).
- [ ] I have included a risk tag of the form `[risk=no|low|moderate|severe]` in the PR title as outlined in [CONTRIBUTING.md](https://github.com/all-of-us/workbench/blob/main/.github/CONTRIBUTING.md).
- [ ] I have manually tested this change and my testing process is described above.
- [ ] This change includes appropriate automated tests, and I have documented any behavior that cannot be tested with code.
- [ ] I have added explanatory comments where the logic is not obvious.
- One or more of the following is true:
  - [ ] This change is intended to complete a JIRA story, so I have checked that all AC are met for that story.
  - [ ] This change fixes a bug, so I have ensured the steps to reproduce are in the Jira ticket or provided above.
  - [ ] This change impacts deployment safety (e.g. removing/altering APIs which are in use), so I have documented the impacts in the description.
  - [ ] This change includes a new feature flag, so I have created and linked new JIRA tickets to (a) turn on the feature flag and (b) remove it later.
  - [ ] This change modifies the UI, so I have taken screenshots or recordings of the new behavior and notified the PO and UX designer in [Slack](https://pmi-engteam.slack.com/archives/C02MWP2RN5P).
  - [ ] This change modifies API behavior, so I have run the relevant E2E tests locally because API changes are not covered by our PR checks.
  - [ ] None of the above apply to this change.

2024-01-09 14:25 UTC, evrii commented on ui/src/app/components/configuration-panel.spec.tsx
These tests were only checking for the presence or absence of the disabled panel, and that is no longer relvant.

2024-01-09 21:20 UTC, evrii commented on ui/src/app/components/apps-panel.spec.tsx
Testing to make sure you cannot click on unexpanded apps when billing is inactive.

2024-01-09 21:20 UTC, evrii commented on ui/src/app/components/apps-panel.tsx
Disabled clicking on unexpanded apps when billing is inactive.

2024-01-09 21:23 UTC, evrii commented on ui/src/app/components/apps-panel/expanded-app.tsx
>  const JupyterButtonRow = (props: {
Disable "Pause and "New Notebook" when billing is inactive.

2024-01-09 21:37 UTC, evrii commented on ui/src/app/components/apps-panel.spec.tsx
Testing to make sure you cannot click on unexpanded apps when billing is inactive.

2024-01-09 21:38 UTC, evrii commented on ui/src/app/components/apps-panel.tsx
Disabled clicking on unexpanded apps when billing is inactive.

2024-01-09 21:40 UTC, evrii commented on ui/src/app/components/apps-panel/expanded-app.tsx
Disable actions that will start environments/apps.

2024-01-09 21:41 UTC, evrii commented on ui/src/app/components/gke-app-configuration-panels/create-gke-app-button.tsx
> -  const createEnabled = !creatingApp && canCreateApp(existingApp);
Clearer logic

2024-01-09 21:42 UTC, evrii commented on ui/src/app/components/apps-panel/utils.tsx
> -export const canCreateApp = (app: UserAppEnvironment): boolean =>
There was only one usage and I replaced that we a clearer usage

2024-01-10 16:53 UTC, Peter-Lavigne requested changes

2024-01-10 16:53 UTC, Peter-Lavigne commented on ui/src/app/components/apps-panel/expanded-app.tsx
> +    ('Environment must be running to launch RStudio');
Should this line assign `tooltip`?

2024-01-10 17:05 UTC, Peter-Lavigne approved these changes

2024-01-10 18:27 UTC, merged